runtime: nodejs18 
env: standard
entrypoint: 'node src/app.js'
env_variables:
  MONDAY_API_KEY: "eyJhbGciOiJIUzI1NiJ9.eyJ0aWQiOjI1Mzk3NTYwNCwiYWFpIjoxMSwidWlkIjo0MjYwMzg4NywiaWFkIjoiMjAyMy0wNS0wMlQwOToxMDo0MC4wMDBaIiwicGVyIjoibWU6d3JpdGUiLCJhY3RpZCI6MTY2ODI1MjIsInJnbiI6ImV1YzEifQ.b-YlSZTbzUQDG2ERvFsZ8dMB3_hv3toFd0klGD62cRY"
  RENTOVER_TENANTS_LEADS_BOARD_ID: 1238615942
  RENTOVER_TENANTS_LEADS_GROUP_NAME: "new_group"
  RENTOVER_TENANTS_DEALS_BOARD_ID: 1196925570
  RENTOVER_TENANTS_DEALS_GROUP_NAME: "new_group"
  RENTOVER_INVESTORS_LEADS_BOARD_ID: 1195562455
  RENTOVER_INVESTORS_LEADS_GROUP_NAME: "new_group"
  RENTOVER_MISSED_LEADS_BOARD_ID: 1195562455
  RENTOVER_MISSED_LEADS_GROUP_NAME: "new_group"
  RENTOVER_UNQUALIFIED_BOARD_ID: 1195562455
  RENTOVER_UNQUALIFIED_GROUP_NAME: "new_group18685"
  SHOWME_CLASSIC_LEADS_BOARD_ID: 1198262442
  SHOWME_CLASSIC_LEADS_GROUP_NAME: "new_group72000"
  SHOWME_MISSED_LEADS_BOARD_ID: 1198262442
  SHOWME_MISSED_LEADS_GROUP_NAME: "new_group72000"
  SHOWME_UNQUALIFIED_BOARD_ID: 1198262442
  SHOWME_UNQUALIFIED_GROUP_NAME: "new_group80583"
  BROKERS_LEADS_BOARD_ID: 1190126591
  BROKERS_LEADS_GROUP_NAME: "new_group39446"
  NEWFORM_MAIN_LEADS_BOARD_ID: 1196019786
  NEWFORM_MAIN_LEADS_GROUP_NAME: "new_group"
  NEWFORM_UNQUALIFIED_BOARD_ID: 1196019786
  NEWFORM_UNQUALIFIED_GROUP_NAME: "new_group9607"
  NEWFORM_MISSED_BOARD_ID: 1196019786
  NEWFORM_MISSED_GROUP_NAME: "new_group"